name : Install Nginx or Local Machine
hosts : local
become : yes # This will use sudo to run tasks with elevated privileges
tasks :
    name : Ensure Nginx is installed
    apt : 
       name : nginx
       state : present 
